version: "3"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./data:/usr/share/nginx/html
    ports:
      - "8080:8080"
    restart: always
