version: "3"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./wwwroot:/usr/share/nginx/html
      #- ./wwwdomain:/usr/share/nginx/wwwdomain
    ports:
      - "8080:80"
    restart: always
