version: "3"
services:
  name:
    container_name: code-server
    image:  codercom/code-server:latest
    volumes:
      - /home/ubuntu:/home/coder/data
      - /home/ubuntu/code-server/config.yaml:/home/coder/.config/code-server/config.yaml
    ports:
      - "8088:8080"
    #environment:
      #- DOCKER_USER=admin
    restart: always
